### ISSUE TITLE
[HELP] getting the latest version of memberterms with get_table_rows

### ISSUE THREAD

**Issue by nanonano7** [eosdac/eosdactoken#10]
i currently can only fetch the first row of the terms table or the whole table.
I would prefer to be able to only get the latest terms sorted by version.

**Comment by lukestokes** [comment]
For now, I'd say just grab the whole table and use the last one. The constitution won't change all that much for it to matter.

**Comment by lukestokes** [comment]
@nanonano7 are you still needing someone to change votes so you can test this?

**Comment by nanonano7** [comment]
yes. but this issue is not related to that. though i still would like to know how to only get the last entry on the memberterms table

**Comment by dallasjohnson** [comment]
There is now the reverse ordered index which covers functionality by allowing you to fetch the last `n` number of rows which would cover this use case.
