### ISSUE TITLE
Add action delete table for development 

### ISSUE THREAD

**Issue by ghost** [eosdac/eosdactoken#12]
Please add an action to delete the table entries. Of course this action can't be integrated on main net. We need to be able to clear the tables to do proper testing. a clear method that accepts the table name as a parameter is  preferred.

**Comment by ghost** [comment]
maybe it's best to create a new dev repo that contains these contracts to prevent confusion.

**Comment by dallasjohnson** [comment]
I have added back the `clear` action but it hasn't worked as expected since the schema has been changed before removing all the rows. I'm trying to fix by adding back the old schema for member and then clearing the rows. Need to keep that in mind for future schema changes.

**Comment by dallasjohnson** [comment]
I think this is pretty dangerous and very rarely needed
