### ISSUE TITLE
Add a bio field for the member

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoken#14]
Note: this is a low priority, but it's something I think we all agree would be useful for the DAC.

In the future, we'll want to explore breaking off the member data from the token contract and potentially store it elsewhere.

**Comment by dallasjohnson** [comment]
I'm pretty sure this has been covered now by the custodian contract's actions. Maybe the next step related to this would be migrate this storage to VRAM and but that's a wider topic.
