### ISSUE TITLE
Add error codes to contract action errors to help with UI and translations

### ISSUE THREAD

**Issue by dallasjohnson** [eosdac/eosdactoken#21]

**Comment by dallasjohnson** [comment]
@kasperfish @michaeljyeates @nanonano7 Please let me know if you have ideas for how you would like to see these errors. From my end I can send text (no control around status codes) only but I could format the contents how you like.

**Comment by ghost** [comment]
we could have our own error codes

**Comment by dallasjohnson** [comment]
Sure. Happy to create our own error codes with a format something like `" error_123456: this is a readable error message"` if that's easy for you to parse on the front end.

**Comment by ghost** [comment]
:-) yeah it would, then we can do a string split with the separator character ':' and use the error code as a key in our multi language files.

**Comment by dallasjohnson** [comment]
Done
