### ISSUE TITLE
Ensure our member registration process stores the constitution version correctly

### ISSUE THREAD

**Issue by lukestokes** [eosdac/eosdactoken#6]
This may have already been done, and if so, please close this, but I want to make sure the latest ideas about this were implemented and pushed to the live EOS Mainnet. If we have changes in the code that haven't been rolled out publicly (such as the ricardian contracts), then we should do a blog post explaining the changes and ensure the interim custodians agree to the changes.

Related: https://github.com/eosdac/eosdactoolkit/issues/4

**Comment by lukestokes** [comment]
Related: https://github.com/eosdac/eosdactoken/pull/7

**Comment by lukestokes** [comment]
@dallasjohnson are we good with this one now? Can we close it?

**Comment by dallasjohnson** [comment]
Done
